[build]
  command = "pnpm run build"

[build.environment]
  NODE_VERSION = "20"

# Disable Edge Functions
[functions]
  external_node_modules = ["sharp"]
  node_bundler = "esbuild"

# Enable Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Let Next.js handle all routing automatically

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://embed.cal.com https://cal.com https://app.cal.com; style-src 'self' 'unsafe-inline' https://embed.cal.com https://cal.com https://app.cal.com; img-src 'self' data: https:; font-src 'self' data: https://embed.cal.com https://cal.com https://app.cal.com; connect-src 'self' https://www.google-analytics.com https://embed.cal.com https://cal.com https://api.cal.com https://app.cal.com; frame-src 'self' https://embed.cal.com https://cal.com https://app.cal.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"